# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
classes:
  - wso2esb
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"

wso2::service_name: wso2esb
wso2::hostname : esb.wso2.com

wso2::file_list :
  - repository/components/lib/mysql-connector-java-5.1.36-bin.jar
#  - repository/components/lib/jackson-annotations-2.5.4.jar
#  - repository/components/lib/jackson-core-2.5.4.jar
#  - repository/components/lib/jackson-databind-2.5.4.jar
#  - repository/components/lib/kubernetes-membership-scheme-1.0.0-SNAPSHOT.jar

wso2::template_list :
  - repository/conf/security/cipher-text.properties
  - repository/conf/security/secret-conf.properties
  - password-persist

wso2::master_datasources :
  wso2_config_db :
    name : WSO2_CONFIG_DB
    description : The datasource used for config registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://172.17.8.1:3306/WSO2REG_DB?autoReconnect=true
    username : root
    password : root
    secret_alias : 'Datasources.WSO2_CONFIG_DB.Configuration.Password'
    jndi_config : jdbc/WSO2_CONFIG_DB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"
  wso2_gov_db :
    name : WSO2_GOV_DB
    description : The datasource used for gov registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://172.17.8.1:3306/WSO2REG_DB?autoReconnect=true
    username : root
    password : root
    secret_alias : 'Datasources.WSO2_GOV_DB.Configuration.Password'
    jndi_config : jdbc/WSO2_GOV_DB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"
  wso2_user_db :
    name : WSO2_USER_DB
    description : The datasource is used for user mangement and userstore
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://172.17.8.1:3306/WSO2_USER_DB?autoReconnect=true
    username : root
    password : root
    secret_alias : 'Datasources.WSO2_USER_DB.Configuration.Password'
    jndi_config : jdbc/WSO2_USER_DB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"